# Generated by Django 4.2.7 on 2023-11-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='csv_db',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('birthplace', models.CharField(max_length=255)),
                ('StudentNumber', models.IntegerField()),
                ('family', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
