# Generated by Django 4.2.7 on 2023-12-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0002_csv_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_db',
            name='birthplace',
            field=models.CharField(max_length=255),
        ),
    ]
