# Generated by Django 4.2.7 on 2023-12-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0003_alter_csv_db_birthplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_db',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
